/** Resumable Google Drive storage for full-game film exported from Hudl or a camera. */
const GAME_FILM_SHEET="Game Film";
const GAME_FILM_HEADERS=["Film ID","Game ID","Team","File Name","MIME Type","Bytes","Status","Drive File ID","Drive URL","Upload URL","Uploaded By","Created At","Updated At","Sync Markers JSON"];
const GAME_FILM_MAX_BYTES=5*1024*1024*1024;
const GAME_FILM_TAGS_SHEET="Game Film Tags";
const GAME_FILM_TAG_HEADERS=["Tag ID","Game ID","Video Seconds","Objective ID","Label","Side","Note","Created By","Created At","Seconds Before","Seconds After"];

function getGameFilm(gameId){requireStaffCapability_("run_sessions");const game=findLiveGameRecord_(gameId).game;requireLiveGameTeamAccess_(game.Team);const record=findGameFilm_(String(gameId));return record?publicGameFilm_(record.values):{gameId:String(gameId),status:"Empty"};}
function beginGameFilmUpload(gameId,metadata){
  requireStaffCapability_("run_sessions");metadata=metadata||{};const game=findLiveGameRecord_(gameId).game;requireLiveGameTeamAccess_(game.Team);if(String(game.Status)!=="Completed")throw new Error("Finish the game before adding film.");
  const name=safeGameFilmText_(metadata.name,180),mime=String(metadata.mimeType||"").toLowerCase(),bytes=Number(metadata.bytes||0);if(!name)throw new Error("Choose a video file.");if(["video/mp4","video/quicktime","video/x-m4v","video/webm"].indexOf(mime)<0)throw new Error("Upload an MP4, MOV, M4V, or WebM video.");if(!Number.isFinite(bytes)||bytes<1||bytes>GAME_FILM_MAX_BYTES)throw new Error("Game film must be smaller than 5 GB.");
  const folder=getCoachIQFilmFolder_(),filmId="FILM-"+Utilities.getUuid().slice(0,12).toUpperCase(),now=new Date(),email=Session.getActiveUser().getEmail()||"";
  const response=UrlFetchApp.fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id%2CwebViewLink",{method:"post",headers:{Authorization:"Bearer "+ScriptApp.getOAuthToken(),"X-Upload-Content-Type":mime,"X-Upload-Content-Length":String(bytes)},contentType:"application/json",payload:JSON.stringify({name:name,mimeType:mime,parents:[folder.getId()]}),muteHttpExceptions:true});
  const uploadUrl=response.getHeaders().Location||response.getHeaders().location;if(response.getResponseCode()<200||response.getResponseCode()>299||!uploadUrl)throw new Error("CoachIQ could not start the film upload.");
  const sheet=initializeGameFilmSheet_(),existing=findGameFilm_(String(gameId),sheet);if(existing){const oldFile=String(existing.values[7]||"");if(oldFile)try{DriveApp.getFileById(oldFile).setTrashed(true);}catch(error){console.error("Previous film cleanup failed: "+error.message);}sheet.deleteRow(existing.rowNumber);}sheet.appendRow([filmId,String(gameId),safeGameFilmText_(game.Team,80),name,mime,bytes,"Uploading","","",uploadUrl,email,now,now]);
  return{filmId:filmId,gameId:String(gameId),status:"Uploading",chunkBytes:3*1024*1024};
}
function uploadGameFilmChunk(filmId,base64,start,end,total){
  requireStaffCapability_("run_sessions");const record=findGameFilmById_(filmId);if(!record)throw new Error("That upload session expired.");requireLiveGameTeamAccess_(String(record.values[2]||""));start=Number(start);end=Number(end);total=Number(total);if(total!==Number(record.values[5])||start<0||end<start||end-start+1>3*1024*1024)throw new Error("Invalid film chunk.");
  const bytes=Utilities.base64Decode(String(base64||""));if(bytes.length!==end-start+1)throw new Error("The film chunk was incomplete.");const response=UrlFetchApp.fetch(String(record.values[9]),{method:"put",headers:{"Content-Range":"bytes "+start+"-"+end+"/"+total},contentType:String(record.values[4]),payload:bytes,muteHttpExceptions:true});const code=response.getResponseCode();
  if(code===308)return{complete:false,nextByte:end+1};if(code<200||code>299)throw new Error("Film upload stopped. Retry the upload.");const result=JSON.parse(response.getContentText()||"{}");const fileId=String(result.id||"");if(!fileId)throw new Error("The uploaded film could not be finalized.");const url=String(result.webViewLink||("https://drive.google.com/file/d/"+fileId+"/view"));record.sheet.getRange(record.rowNumber,7,1,7).setValues([["Ready",fileId,url,"",record.values[10],record.values[11],new Date()]]);return{complete:true,film:publicGameFilm_(record.sheet.getRange(record.rowNumber,1,1,GAME_FILM_HEADERS.length).getValues()[0])};
}
function deleteGameFilm(gameId){requireStaffCapability_("run_sessions");const record=findGameFilm_(String(gameId));if(!record)return{success:true};requireLiveGameTeamAccess_(String(record.values[2]||""));const fileId=String(record.values[7]||"");if(fileId)try{DriveApp.getFileById(fileId).setTrashed(true);}catch(error){console.error("Film file cleanup failed: "+error.message);}record.sheet.deleteRow(record.rowNumber);return{success:true};}
function saveGameFilmSync(gameId,markers){requireStaffCapability_("run_sessions");const record=findGameFilm_(String(gameId));if(!record||String(record.values[6])!=="Ready")throw new Error("Upload the game film before syncing it.");requireLiveGameTeamAccess_(String(record.values[2]||""));const anchors=buildGameFilmSyncAnchors_(gameId),allowed={};anchors.forEach(function(item){if(item.available)allowed[item.period]=true;});const cleaned={};Object.keys(markers||{}).forEach(function(key){const period=Number(key),seconds=Number(markers[key]);if(allowed[period]&&Number.isFinite(seconds)&&seconds>=0&&seconds<=43200)cleaned[period]=Math.round(seconds*10)/10;});if(!Object.keys(cleaned).length)throw new Error("Enter at least one valid video time.");record.sheet.getRange(record.rowNumber,14).setValue(JSON.stringify(cleaned));record.sheet.getRange(record.rowNumber,13).setValue(new Date());return publicGameFilm_(record.sheet.getRange(record.rowNumber,1,1,GAME_FILM_HEADERS.length).getValues()[0]);}
function initializeGameFilmSheet_(){const ss=getCoachIQSpreadsheet_();let sheet=ss.getSheetByName(GAME_FILM_SHEET);if(!sheet){sheet=ss.insertSheet(GAME_FILM_SHEET);sheet.getRange(1,1,1,GAME_FILM_HEADERS.length).setValues([GAME_FILM_HEADERS]);sheet.setFrozenRows(1);sheet.hideSheet();}else if(sheet.getLastColumn()<GAME_FILM_HEADERS.length){sheet.getRange(1,sheet.getLastColumn()+1,1,GAME_FILM_HEADERS.length-sheet.getLastColumn()).setValues([GAME_FILM_HEADERS.slice(sheet.getLastColumn())]);}return sheet;}
function getCoachIQFilmFolder_(){const props=PropertiesService.getScriptProperties(),saved=props.getProperty("COACHIQ_FILM_FOLDER_ID");if(saved)try{return DriveApp.getFolderById(saved);}catch(error){}const folder=DriveApp.createFolder("CoachIQ Game Film");props.setProperty("COACHIQ_FILM_FOLDER_ID",folder.getId());return folder;}
function findGameFilm_(gameId,sheet){sheet=sheet||initializeGameFilmSheet_();if(sheet.getLastRow()<2)return null;const rows=sheet.getRange(2,1,sheet.getLastRow()-1,GAME_FILM_HEADERS.length).getValues();for(let i=rows.length-1;i>=0;i--)if(String(rows[i][1])===gameId)return{sheet:sheet,rowNumber:i+2,values:rows[i]};return null;}
function findGameFilmById_(filmId){const sheet=initializeGameFilmSheet_();if(sheet.getLastRow()<2)return null;const rows=sheet.getRange(2,1,sheet.getLastRow()-1,GAME_FILM_HEADERS.length).getValues();for(let i=0;i<rows.length;i++)if(String(rows[i][0])===String(filmId))return{sheet:sheet,rowNumber:i+2,values:rows[i]};return null;}
function publicGameFilm_(row){const gameId=String(row[1]||""),markers=parseLiveGameObject_(row[13],{}),game=findLiveGameRecord_(gameId).game,gameFormat=String(game["Game Format"]||"Quarters");return{filmId:String(row[0]||""),gameId:gameId,gameFormat:gameFormat,fileName:String(row[3]||""),mimeType:String(row[4]||""),bytes:Number(row[5]||0),status:String(row[6]||"Empty"),watchUrl:String(row[8]||""),updatedAt:row[12] instanceof Date?row[12].toISOString():String(row[12]||""),syncMarkers:markers,syncAnchors:buildGameFilmSyncAnchors_(gameId),timeline:buildGameFilmTimeline_(gameId,markers)};}
function buildGameFilmSyncAnchors_(gameId){const events=getLiveGameEvents_(gameId),first={},labels=gameFilmObjectiveLabels_(gameId),game=findLiveGameRecord_(gameId).game,format=String(game["Game Format"]||"Periods");events.forEach(function(event){if(!first[event.period])first[event.period]=event;});let expected=0,name=format.toLowerCase(),match=name.match(/(\d+)\s*(?:innings|sets)/);if(name.indexOf("halves")>=0||name.indexOf("half")>=0)expected=2;else if(name.indexOf("quarter")>=0)expected=4;else if(match)expected=Number(match[1]);events.forEach(function(event){expected=Math.max(expected,Number(event.period||0));});return Array.from({length:expected},function(_,index){const period=index+1,event=first[period];return event?{period:period,available:true,eventId:event.eventId,label:gameFilmEventLabel_(event,labels),timestamp:event.timestamp}:{period:period,available:false,label:"No tracked events in this period"};});}
function buildGameFilmTimeline_(gameId,markers){const events=getLiveGameEvents_(gameId),firstByPeriod={},labels=gameFilmObjectiveLabels_(gameId);events.forEach(function(event){if(!firstByPeriod[event.period])firstByPeriod[event.period]=gameFilmEventTime_(event.timestamp);});return events.map(function(event){const anchor=Number(markers&&markers[event.period]),eventTime=gameFilmEventTime_(event.timestamp),first=firstByPeriod[event.period];if(!Number.isFinite(anchor)||!eventTime||!first)return null;return{eventId:event.eventId,period:event.period,gameClock:event.gameClock,label:gameFilmEventLabel_(event,labels),videoSeconds:Math.max(0,Math.round((anchor+(eventTime-first)/1000)*10)/10)};}).filter(Boolean);}
function gameFilmEventTime_(value){const date=new Date(String(value||"").replace(" ","T"));return isNaN(date.getTime())?0:date.getTime();}
function gameFilmObjectiveLabels_(gameId){const game=findLiveGameRecord_(gameId).game,original=parseLiveGameJson_(game["Tracking Plan"],[]),active=parseLiveGameJson_(game["Active Tracking Plan"],original),labels={};active.concat(original).forEach(function(item){if(item&&item.id)labels[String(item.id)]=String(item.label||item.id);});return labels;}
function gameFilmEventLabel_(event,labels){const raw=String(event.eventType||"Event"),label=(labels&&labels[raw])||raw.replace(/^(?:objective|custom)_/i,"").replace(/_[a-z0-9]{6,}$/i,"").replace(/_/g," ").replace(/\b\w/g,function(letter){return letter.toUpperCase();});return(event.side==="Opponent"?"Opponent · ":"")+label;}
function safeGameFilmText_(value,max){const text=String(value||"").trim().slice(0,max);return/^[=+\-@]/.test(text)?"'"+text:text;}

function getGameFilmReviewData(gameId){requireStaffCapability_("run_sessions");const record=findLiveGameRecord_(gameId),game=record.game;requireLiveGameTeamAccess_(game.Team);const objectives=parseLiveGameJson_(game["Active Tracking Plan"],parseLiveGameJson_(game["Tracking Plan"],[])).filter(function(item){return item&&item.active!==false;}).map(function(item){return{id:String(item.id||""),label:String(item.label||"Tracking item"),subject:String(item.subject||"our_team")};});return{gameId:String(gameId),team:String(game.Team||"Our team"),opponent:String(game.Opponent||"Opponent"),objectives:objectives,tags:getGameFilmReviewTags_(String(gameId))};}
function saveGameFilmReviewTag(gameId,tag){requireStaffCapability_("run_sessions");tag=tag||{};const record=findLiveGameRecord_(gameId),game=record.game;requireLiveGameTeamAccess_(game.Team);if(String(game.Status||"")!=="Completed")throw new Error("Finish the game before reviewing its film.");const objectives=parseLiveGameJson_(game["Active Tracking Plan"],parseLiveGameJson_(game["Tracking Plan"],[])),objective=objectives.find(function(item){return String(item.id||"")===String(tag.objectiveId||"")&&item.active!==false;});if(!objective)throw new Error("Choose a game-plan priority.");const seconds=Math.round(Number(tag.videoSeconds)*10)/10;if(!Number.isFinite(seconds)||seconds<0||seconds>43200)throw new Error("Choose a valid moment in the film.");const side=tag.side==="Opponent"?"Opponent":"Our Team",tagId="TAG-"+Utilities.getUuid().slice(0,12).toUpperCase(),sheet=initializeGameFilmTagsSheet_();sheet.appendRow([tagId,String(gameId),seconds,String(objective.id),safeGameFilmText_(objective.label,60),side,safeGameFilmText_(tag.note,240),Session.getActiveUser().getEmail()||"",new Date(),5,10]);return getGameFilmReviewData(gameId);}
function updateGameFilmReviewClip(gameId,tagId,beforeSeconds,afterSeconds){requireStaffCapability_("run_sessions");const game=findLiveGameRecord_(gameId).game;requireLiveGameTeamAccess_(game.Team);beforeSeconds=Math.round(Number(beforeSeconds));afterSeconds=Math.round(Number(afterSeconds));if(!Number.isFinite(beforeSeconds)||!Number.isFinite(afterSeconds)||beforeSeconds<0||beforeSeconds>60||afterSeconds<1||afterSeconds>120)throw new Error("Use 0–60 seconds before and 1–120 seconds after the tag.");const sheet=initializeGameFilmTagsSheet_(),rows=sheet.getLastRow()>1?sheet.getRange(2,1,sheet.getLastRow()-1,GAME_FILM_TAG_HEADERS.length).getValues():[],index=rows.findIndex(function(row){return String(row[0])===String(tagId)&&String(row[1])===String(gameId);});if(index<0)throw new Error("That film moment was not found.");sheet.getRange(index+2,10,1,2).setValues([[beforeSeconds,afterSeconds]]);return getGameFilmReviewData(gameId);}
function deleteGameFilmReviewTag(gameId,tagId){requireStaffCapability_("run_sessions");const game=findLiveGameRecord_(gameId).game;requireLiveGameTeamAccess_(game.Team);const sheet=initializeGameFilmTagsSheet_();if(sheet.getLastRow()>1){const rows=sheet.getRange(2,1,sheet.getLastRow()-1,GAME_FILM_TAG_HEADERS.length).getValues();for(let i=rows.length-1;i>=0;i--)if(String(rows[i][0])===String(tagId)&&String(rows[i][1])===String(gameId)){sheet.deleteRow(i+2);break;}}return getGameFilmReviewData(gameId);}
function initializeGameFilmTagsSheet_(){const ss=getCoachIQSpreadsheet_();let sheet=ss.getSheetByName(GAME_FILM_TAGS_SHEET);if(!sheet){sheet=ss.insertSheet(GAME_FILM_TAGS_SHEET);sheet.getRange(1,1,1,GAME_FILM_TAG_HEADERS.length).setValues([GAME_FILM_TAG_HEADERS]);sheet.setFrozenRows(1);sheet.hideSheet();}else if(sheet.getLastColumn()<GAME_FILM_TAG_HEADERS.length){sheet.getRange(1,sheet.getLastColumn()+1,1,GAME_FILM_TAG_HEADERS.length-sheet.getLastColumn()).setValues([GAME_FILM_TAG_HEADERS.slice(sheet.getLastColumn())]);}return sheet;}
function getGameFilmReviewTags_(gameId){const sheet=initializeGameFilmTagsSheet_();if(sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,GAME_FILM_TAG_HEADERS.length).getValues().filter(function(row){return String(row[1])===gameId;}).map(function(row){return{tagId:String(row[0]),videoSeconds:Number(row[2]||0),objectiveId:String(row[3]),label:String(row[4]),side:String(row[5]),note:String(row[6]||""),beforeSeconds:row[9]===""?5:Number(row[9]),afterSeconds:row[10]===""?10:Number(row[10])};}).sort(function(a,b){return a.videoSeconds-b.videoSeconds;});}
