const fs=require("node:fs");
const path=require("node:path");
const test=require("node:test");
const assert=require("node:assert/strict");
const root=path.join(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("completed games retain an optional full-film cloud upload",()=>{const game=read("Game.html"),scripts=read("Scripts.html");assert.match(game,/Optional: keep a cloud copy in CoachIQ/);assert.match(game,/up to 5 GB/);assert.match(scripts,/openGameFilm/);assert.match(scripts,/uploadSelectedGameFilm/);assert.match(scripts,/uploadGameFilmChunks_/);assert.match(scripts,/function gameFilmMimeType_/);});
test("film upload uses resumable Drive storage rather than spreadsheet blobs",()=>{const service=read("FilmService.gs");assert.match(service,/uploadType=resumable/);assert.match(service,/Content-Range/);assert.match(service,/3\*1024\*1024/);assert.match(service,/Drive File ID/);assert.doesNotMatch(service,/appendRow\([^\n]*base64/);});
test("film endpoints protect completed games and team access",()=>{const service=read("FilmService.gs");assert.match(service,/requireStaffCapability_\("run_sessions"\)/);assert.match(service,/requireLiveGameTeamAccess_/);assert.match(service,/game\.Status\)!=="Completed"/);assert.match(service,/GAME_FILM_MAX_BYTES=5\*1024\*1024\*1024/);});
test("clockless film can be synchronized with one tracked event per period",()=>{const game=read("Game.html"),service=read("FilmService.gs"),scripts=read("Scripts.html");assert.match(game,/Quick Sync uses one known event per period/);assert.match(service,/Sync Markers JSON/);assert.match(service,/function saveGameFilmSync/);assert.match(service,/function buildGameFilmSyncAnchors_/);assert.match(service,/function buildGameFilmTimeline_/);assert.match(scripts,/function openGameFilmSync/);assert.match(scripts,/function parseGameFilmTime_/);assert.match(scripts,/function renderGameFilmTimeline_/);});
test("film sync validates anchors and never requires re-tagging events",()=>{const service=read("FilmService.gs");assert.match(service,/seconds>=0&&seconds<=43200/);assert.match(service,/getLiveGameEvents_\(gameId\)/);assert.match(service,/anchor\+\(eventTime-first\)\/1000/);});
test("quick sync respects halves, quarters, periods, innings, and sets",()=>{const service=read("FilmService.gs"),scripts=read("Scripts.html");assert.match(service,/gameFormat:gameFormat/);assert.match(service,/game\["Game Format"\]/);assert.match(scripts,/liveGamePeriodName\(film\.gameFormat,anchor\.period\)/);assert.match(scripts,/liveGamePeriodName\(film\.gameFormat,event\.period\)/);assert.doesNotMatch(scripts,/liveGamePeriodName\("Quarters",anchor\.period\)/);});
test("plural Halves renders first and second half labels",()=>{const scripts=read("Scripts.html"),source=scripts.match(/function liveGamePeriodName\(format,period\)\{[\s\S]*?\n\}/)[0],liveGamePeriodName=Function(source+";return liveGamePeriodName;")();assert.equal(liveGamePeriodName("Halves",1),"First Half");assert.equal(liveGamePeriodName("Halves",2),"Second Half");assert.equal(liveGamePeriodName("Halves",3),"OT 1");assert.equal(liveGamePeriodName("Quarters",2),"Quarter 2");});
test("quick sync explains missing periods and resolves objective labels",()=>{const service=read("FilmService.gs"),scripts=read("Scripts.html");assert.match(service,/No tracked events in this period/);assert.match(service,/function gameFilmObjectiveLabels_/);assert.match(service,/Tracking Plan/);assert.match(service,/available:false/);assert.match(scripts,/Nothing to sync/);assert.match(scripts,/anchor\.available/);});
test("saved sync markers are read back as an object before building the timeline",()=>{const service=read("FilmService.gs");assert.match(service,/markers=parseLiveGameObject_\(row\[13\],\{\}\)/);assert.doesNotMatch(service,/markers=parseLiveGameJson_\(row\[13\],\{\}\)/);});

test("local film review turns selected game-plan priorities into saved coaching moments",()=>{const game=read("Game.html"),service=read("FilmService.gs"),scripts=read("Scripts.html"),styles=read("Styles.html");assert.match(game,/Choose film to review/);assert.match(game,/it is not uploaded/);assert.match(game,/gameFilmReviewVideo/);assert.match(game,/Tag what matters/);assert.match(service,/function getGameFilmReviewData/);assert.match(service,/function saveGameFilmReviewTag/);assert.match(service,/Game Film Tags/);assert.match(service,/Active Tracking Plan/);assert.match(scripts,/video\.currentTime/);assert.match(scripts,/function tagGameFilmMoment/);assert.match(scripts,/Category playlists/);assert.match(scripts,/jumpToGameFilmTag/);assert.match(styles,/game-film-review-buttons/);});
test("film review tags remain protected and limited to completed accessible games",()=>{const service=read("FilmService.gs");assert.match(service,/requireStaffCapability_\("run_sessions"\)/);assert.match(service,/requireLiveGameTeamAccess_\(game\.Team\)/);assert.match(service,/Finish the game before reviewing its film/);assert.match(service,/seconds>43200/);assert.match(service,/safeGameFilmText_\(tag\.note,240\)/);});
test("film review can use the entire available viewport",()=>{const game=read("Game.html"),scripts=read("Scripts.html"),styles=read("Styles.html");assert.match(game,/gameFilmFullscreenButton/);assert.match(game,/Full screen/);assert.match(scripts,/function toggleGameFilmFullscreen/);assert.match(scripts,/requestFullscreen/);assert.match(scripts,/fullscreenchange/);assert.match(scripts,/classList\.add\("film-review-mode"\)/);assert.match(scripts,/classList\.remove\("film-review-mode"\)/);assert.match(styles,/body\.film-review-mode #sidebar/);assert.match(styles,/width:100vw;height:100vh/);assert.match(styles,/height:calc\(100vh - 235px\)/);});
test("film review has playback controls and hold-to-speed shortcuts",()=>{const game=read("Game.html"),scripts=read("Scripts.html"),styles=read("Styles.html");assert.match(game,/↶ 5 sec/);assert.match(game,/5 sec ↷/);assert.match(game,/Slower/);assert.match(game,/Hold 2×/);assert.match(game,/Hot keys:/);assert.match(scripts,/function toggleGameFilmPlayback/);assert.match(scripts,/function skipGameFilmReview/);assert.match(scripts,/function setGameFilmSpeed/);assert.match(scripts,/function beginGameFilmHoldSpeed/);assert.match(scripts,/function endGameFilmHoldSpeed/);assert.match(scripts,/filmHoldSpeedPrevious/);assert.match(scripts,/addEventListener\("keyup"/);assert.match(scripts,/target\.isContentEditable/);assert.match(game,/skipGameFilmReview\(-5\)/);assert.match(game,/skipGameFilmReview\(5\)/);assert.match(styles,/game-film-playback-tools/);});
test("film tags become editable category playlists",()=>{const service=read("FilmService.gs"),scripts=read("Scripts.html"),styles=read("Styles.html");assert.match(service,/Seconds Before/);assert.match(service,/Seconds After/);assert.match(service,/function updateGameFilmReviewClip/);assert.match(service,/beforeSeconds<0\|\|beforeSeconds>60/);assert.match(service,/afterSeconds<1\|\|afterSeconds>120/);assert.match(scripts,/Category playlists/);assert.match(scripts,/function playGameFilmPlaylist/);assert.match(scripts,/function advanceGameFilmPlaylist_/);assert.match(scripts,/function updateGameFilmClipWindow_/);assert.match(scripts,/Clip length saved/);assert.match(styles,/game-film-playlists/);assert.match(styles,/game-film-clip-window/);});
test("each saved moment plays as an individual bounded clip",()=>{const scripts=read("Scripts.html");assert.match(scripts,/Play clip ·/);assert.match(scripts,/function playGameFilmClip/);assert.match(scripts,/tags:\[tag\]/);assert.match(scripts,/single:true/);assert.match(scripts,/Clip complete/);assert.match(scripts,/video\.pause\(\)/);assert.match(scripts,/cloud film copy is required before a player link can be published/);});
test("opening a category shows only its individual clips",()=>{const scripts=read("Scripts.html"),styles=read("Styles.html");assert.match(scripts,/function openGameFilmPlaylist/);assert.match(scripts,/function closeGameFilmPlaylist/);assert.match(scripts,/Open clips →/);assert.match(scripts,/← All playlists/);assert.match(scripts,/visibleTags=selected\?selected\.tags:\[\]/);assert.match(scripts,/list\.hidden=!selected/);assert.match(styles,/game-film-playlist-header/);assert.match(styles,/game-film-clip-main/);assert.match(styles,/game-film-clip-edit/);});
